### ISSUE TITLE
Zoom Issues

### ISSUE THREAD

**Issue by boonkerz** [catppuccin/egui#1]
Zoom Issue because of setting ctx.set_pixels_per_point(1.25);

my app switches between 2.0 and 1.25

**Comment by backwardspy** [comment]
hi! thanks for raising this issue. i have replicated the bug and we will get a fix out for it shortly. apologies for the inconvenience!

**Comment by Stonks3141** [comment]
This is fixed by a0a4719a52e20f012dfb11a9102ac2d37e97a2f3.
