### ISSUE TITLE
Update README version automatically

### ISSUE THREAD

**Issue by MCOfficer** [catppuccin/egui#26]
It seems like the thing that can be automated, and indeed, cargo release can do it:

https://github.com/crate-ci/cargo-release/blob/master/docs/faq.md#how-do-i-update-my-readme-or-other-files

Is this something you would like to use for releases? If so, would you like a PR?

**Comment by Stonks3141** [comment]
Yes, that would be great!

**Comment by MCOfficer** [comment]
Seems like cargo release only supports full version numbers - that's to say, your nice `4.0` would become a  `4.0.0`. Is that ok? Alternatively, we can use github actions to automate 6b37add059c10b4ae8e3148f7026303b50d05c0c: on every release, regex Cargo.toml, update the README, and commit the change.

**Comment by Stonks3141** [comment]
Can it add a "^" in front of the `4.0.0` so Cargo will still be able to use later patch versions? If not, probably best to just use it anyway. Updating manually would just be a blob of fragile and inscrutable shell script.

**Comment by MCOfficer** [comment]
That's possible, yes.

**Comment by Stonks3141** [comment]
Closed by #28.
