### ISSUE TITLE
Wrong button color?

### ISSUE THREAD

**Issue by njust** [catppuccin/egui#3]
Hi, I tried the todo example with the "LATTE" theme and noticed that the contrast of text color on the buttons is bad. The colors also do not match the screenshots on the readme, so I suppose it's a bug?
![image](https://user-images.githubusercontent.com/2380253/227370547-9dc217cf-4e8a-4b37-bac1-3c31b8655e2c.png)

**Comment by Speak2Erase** [comment]
I'm also seeing this problem too!

**Comment by Stonks3141** [comment]
Thanks for reporting! This should be fixed by 7f606c3b7f4f45d4672ae92cc4b20d774866920a.

**Comment by Stonks3141** [comment]
Patch is out!
