### ISSUE TITLE
v5.0.0 did not get published on crates.io

### ISSUE THREAD

**Issue by MCOfficer** [catppuccin/egui#33]
Not sure why, but the cargo-release CI didn't even trigger.

**Comment by Stonks3141** [comment]
MCOfficer ***@***.***> wrote:
> Not sure why, but the cargo-release CI didn't even trigger.

Oh yeah, that's my bad, I made some changes to the CI and noticed that 
it didn't trigger when I cut the release but I haven't had time lately 
to fix it yet. It seems like release-please somehow doesn't trigger 
github's "tag pushed" event for Actions. Thanks for reminding me!

**Comment by MCOfficer** [comment]
I know github has some protection against circular pipelines, for instance a commit by the CI user won't trigger the push-event. I guess something similar is happening here - maybe the release event works instead?

```yaml
on:
  release:
    types:
      - published
```

**Comment by Stonks3141** [comment]
I love github actions actually

**Comment by sgoudham** [comment]
Sorry I meant to reply this a long time ago. 

I don't believe we're using release please in a way that benefits us here. 

Release please allows you to run a specific step/job based on if the release please PR was merged. See [mdbook](https://github.com/catppuccin/mdBook/blob/9b436bf09bec634bf797a0b363249c718b6fa332/.github/workflows/release.yml#L27-L41) as an example.

I think you'd just have one single CI file that runs release please and your normal build. If a release was created, you'd run another job to publish to crates.io

**Comment by Stonks3141** [comment]
@sgoudham if you don't mind, I'd like you to review #36 and see if it is what you wanted!
