### ISSUE TITLE
selection of egui version via cargo features

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [catppuccin/egui#34]
Hi there,

i think this repository has exposed types of egui and needs to be in sync with egui releases of the used rust project. Nevertheless, i found similar crates suffering of the same dependency management problem, like the create egui_struct. I have seen there, that they found a quite elegant solution in my eyes, where they expose the egui dependency selection via cargo features:

See here:
https://github.com/PingPongun/egui_struct/blob/master/Cargo.toml

Maybe the same approach is good applicable here?

best,
Christian

**Comment by Stonks3141** [comment]
Thanks, this looks much better than the current "constantly bump the major version because semver" strategy! I think ideally we would have just kept our version in sync with egui's, but that ship sailed the day I released 1.0. I'll try this for the next egui version bump.
